networks:
  postgresql:
    driver: bridge
  images:
    driver: bridge
  bracket:
    driver: bridge

volumes:
  pgdata:

services:
  postgres:  
    container_name: postgresql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dbcbot/migrations:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  dbc-bot:
    image: mcr.microsoft.com/devcontainers/rust:dev-bullseye   
    container_name: dbc-bot
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      IMAGES_API: "http://images:${IMAGES_PORT}"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      BRAWL_STARS_TOKEN: ${BRAWL_STARS_TOKEN}
      SQLX_OFFLINE: ${SQLX_OFFLINE}
    networks:
      - postgresql
      - images
    volumes:
      - /etc/ssl/certs/:/etc/ssl/certs:ro
      - .:/workspace:cached
    restart: always
    depends_on:
      - postgres
      - images
    command: sleep infinity
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"

  images:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    container_name: images-server
    environment:
      PORT: ${IMAGES_PORT}
    ports:
      - "${IMAGES_PORT}:${IMAGES_PORT}"
    volumes:
      - .:/workspace:cached
    restart: always
    networks:
      - images
    command: sleep infinity
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
    
  bracket:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bookworm
    container_name: bracket
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    ports:
      - "${BRACKET_PORT}:${BRACKET_PORT}"
    volumes:
      - .:/usr/src/app
      - .:/workspace:cached
    depends_on:
      - postgres
    networks:
      - postgresql
      - bracket
    restart: always
    command: sleep infinity
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "20"
