name: Write token to .env in remote
on:
  workflow_dispatch:

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
      - name: Create .env file on droplet
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/dbcbot || exit 1
            echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" > ./.token.env
